name: 'Build'
on:
  push: { }
permissions:
  contents: 'write'
jobs:
  build-first:
    runs-on: 'ubuntu-latest'
    steps:
      # https://github.com/hmarr/debug-action
      - uses: 'hmarr/debug-action@v3' # v3.0.0

      # https://github.com/actions/checkout
      - name: 'checkout'
        uses: 'actions/checkout@v4' # v4.1.7

      # https://github.com/actions/setup-java
      - name: 'Set up JDK'
        uses: 'actions/setup-java@v4' # v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'

      # https://github.com/gradle/actions/tree/main/setup-gradle
      - name: 'Set up Gradle'
        uses: 'gradle/actions/setup-gradle@6c9e5473141d9a428221ea9a229a025d7bf331d4' # v4.0.0-beta.1
        with:
          validate-wrappers: true

        # https://github.com/gradle/actions/tree/main/dependency-submission
      #    - name: "Generate and submit dependency graph"
      #      uses: 'gradle/actions/setup-gradle@6c9e5473141d9a428221ea9a229a025d7bf331d4' # v4.0.0-beta.1
      #      env:
      #        dependency-graph-report-dir: "${{ github.workspace }}/build/dependency-graph-reports"
      #        dependency-graph-exclude-projects: "^:(build-logic|buildSrc|.*[Tt]test.*)"
      #        dependency-graph-exclude-configurations: ".*[Tt]est.*Classpath"

      - name: 'Build'
        run: './gradlew build --info --scan --stacktrace --build-file build.gradle.kts'

  build-second:
    runs-on: 'ubuntu-latest'
    needs: [ 'build-first' ]
    steps:
      # https://github.com/hmarr/debug-action
      - uses: 'hmarr/debug-action@v3' # v3.0.0

      # https://github.com/actions/checkout
      - name: 'checkout'
        uses: 'actions/checkout@v4' # v4.1.7

      # https://github.com/actions/setup-java
      - name: 'Set up JDK'
        uses: 'actions/setup-java@v4' # v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'

      # https://github.com/gradle/actions/tree/main/setup-gradle
      - name: 'Set up Gradle'
        uses: 'gradle/actions/setup-gradle@6c9e5473141d9a428221ea9a229a025d7bf331d4' # v4.0.0-beta.1
        with:
          validate-wrappers: true

        # https://github.com/gradle/actions/tree/main/dependency-submission
      #    - name: "Generate and submit dependency graph"
      #      uses: 'gradle/actions/setup-gradle@6c9e5473141d9a428221ea9a229a025d7bf331d4' # v4.0.0-beta.1
      #      env:
      #        dependency-graph-report-dir: "${{ github.workspace }}/build/dependency-graph-reports"
      #        dependency-graph-exclude-projects: "^:(build-logic|buildSrc|.*[Tt]test.*)"
      #        dependency-graph-exclude-configurations: ".*[Tt]est.*Classpath"

      - name: 'Build'
        run: './gradlew build --info --scan --stacktrace --build-file build-second.gradle.kts'
