name: 'Build'
on:
  push: { }

permissions:
  contents: read

jobs:
  build-first:
    uses: ./.github/workflows/run-gradle.yml

  build-second:
    needs: [ 'build-first' ]
    uses: ./.github/workflows/run-gradle.yml
