name: 'Build'
on:
  push:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
    group: 'the-concurrency-group'
    cancel-in-progress: true

jobs:
  build-first:
    strategy:
      matrix:
        log-level: [ 'info', 'debug' ]
    uses: ./.github/workflows/run-gradle.yml
    with:
      task-name: help
      log-level: ${{ matrix.log-level }}

  build-second:
    needs: [ 'build-first' ]
    strategy:
      matrix:
        log-level: [ 'info', 'debug' ]
    uses: ./.github/workflows/run-gradle.yml
    with:
      task-name: assemble
      log-level: ${{ matrix.log-level }}
