name: 'Build'
on:
  push: { }

permissions:
  contents: read

jobs:
  debugging:
    runs-on: ubuntu-latest
    steps:
      - uses: 'hmarr/debug-action@v3'

  build-first:
    needs: [ 'debugging' ]
    uses: ./.github/workflows/run-gradle.yml

  build-second:
    needs: [ 'build-first' ]
    uses: ./.github/workflows/run-gradle.yml
