name: 'Build'
on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-help:
    strategy:
      matrix:
        log-level: [ 'info', 'quiet' ]
    uses: ./.github/workflows/run-gradle.yml
    with:
      task-name: help
      log-level: ${{ matrix.log-level }}

  build-assemble:
    needs: [ 'build-help' ]
    strategy:
      matrix:
        log-level: [ 'info', 'quiet' ]
    uses: ./.github/workflows/run-gradle.yml
    with:
      task-name: assemble
      log-level: ${{ matrix.log-level }}

  job-without-name:
    runs-on: ubuntu-latest
    steps:
    - name: Dump script context
      uses: actions/github-script@v7
      with:
        script: console.log(context)

  job-with-name:
    name: The Job Name
    runs-on: ubuntu-latest
    steps:
    - name: Dump script context
      uses: actions/github-script@v7
      with:
        script: console.log(context)
