name: Gradle Task
run-name: "Gradle Task ${{ inputs.task }}, ${{ inputs.runs-on }}, ${{ inputs.ref }}"

on:
  workflow_call:
    inputs:
      task-name:
        required: true
        type: string
      log-level:
        required: true
        type: string

permissions:
  contents: read

jobs:
  run-tests:
    strategy:
      matrix:
       arg: ['--scan', '--stacktrace']
    runs-on: ubuntu-latest
    steps:
      - uses: 'hmarr/debug-action@v3'

      - name: grab job id
        shell: bash
        run: |
          set -x
          job_url="https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/jobs"
          job_json=$(curl -v -s -H "Authorization: token ${{ github.token }}" $job_url | jq)
          job_id=$(curl -v -s -H "Authorization: token ${{ github.token }}" $job_url | jq -r '.jobs[] | .id')
          echo $job_json
          echo $job_id

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - name: Dump inputs context
        env:
          INPUTS_CONTEXT: ${{ toJson(inputs) }}
        run: echo "$INPUTS_CONTEXT"

      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@main
        with:
          cache-read-only: false

      - name: Run Gradle
        run: ./gradlew ${{ inputs.task-name }} --${{ inputs.log-level }} ${{ matrix.arg }}
